version: '2'
services:
  aliyuncode:
    # build: ./docker
    image: registry.cn-hangzhou.aliyuncs.com/jinyongyang/aliyuncode:latest
    container_name: aliyuncode
    ports:
      - 8086:8086
    environment:
      RUNCOMMAND: "/usr/java/jdk1.8.0_45/bin/java -jar /srv/aliyuncode/SpringBootRest.jar"

  